# Generated by Django 4.1.3 on 2022-11-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='id_categoria',
        ),
    ]
