# Generated by Django 4.1.3 on 2022-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
