# Generated by Django 4.1.3 on 2022-11-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
