# Generated by Django 4.1.3 on 2022-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_actividades_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='nombre_comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
