# Generated by Django 4.1.3 on 2022-11-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_comentarios_nombre_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='nombre_comentario',
            new_name='usuario_comentario',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='id_actividad',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='id_usuario',
        ),
    ]
