# Generated by Django 4.1.3 on 2022-11-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_alter_actividades_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='id',
        ),
        migrations.AlterField(
            model_name='actividades',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.categorias'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
