# Generated by Django 4.1.3 on 2022-11-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_rename_nombre_comentario_comentarios_usuario_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='id_comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
